name: bmi_calculator  # The name of your app (in lowercase)
description: "A new Flutter project to calculate BMI."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Add this line to include the launcher icons package

flutter:
  uses-material-design: true

flutter_icons:
  android: true  # Enable app icon generation for Android
  ios: true  # Enable app icon generation for iOS
  image_path: "assets/icons/unnamed.png"  # Path to your app icon image
